version: '3.1'
services: 
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    restart: always
    volumes: 
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 9000:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: 12qwaszx
    networks:
      - back

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12qwaszx
    networks:
      - back

networks:
  back:

volumes:
  db_data:
